import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { root, productIds, readProduct } from '../src/compiler.mjs';

const destination = resolve(process.argv[2] || join(root, 'dist/preview.html'));
const messages = JSON.parse(readFileSync(join(root, 'locales/messages.json')));
const products = productIds.map(id => ({ ...readProduct(id), image: `data:image/png;base64,${readFileSync(join(root, 'assets', id, 'sidebar.png')).toString('base64')}` }));
const data = JSON.stringify({ products, messages }).replaceAll('<', '\\u003c');
const html = `<!doctype html><html lang="zh-Hans"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Desktop Installer · Preview</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f5f5f5;color:#252528;font:14px/1.55 system-ui,-apple-system,"Segoe UI","Microsoft YaHei",sans-serif}main{max-width:1060px;margin:56px auto;padding:0 28px}h1{font-size:30px;letter-spacing:-.8px;margin:0 0 8px;font-weight:650}header p{color:#68686d;max-width:720px;margin:0}.controls{display:flex;flex-wrap:wrap;gap:20px;margin:32px 0 22px;align-items:center}label{display:flex;gap:9px;align-items:center}select,button{font:inherit;color:inherit;background:white;border:1px solid #bcbcc1;border-radius:4px;padding:5px 11px}button{cursor:pointer}button:focus-visible,select:focus-visible,a:focus-visible{outline:2px solid #303038;outline-offset:3px}.surface{overflow-x:auto;padding:2px 2px 24px}.window{width:680px;background:#fff;border:1px solid #bfbfc3;border-radius:7px;overflow:hidden}.titlebar{height:36px;display:flex;align-items:center;padding:0 13px;font-size:12px;border-bottom:1px solid #ededee}.close{margin-left:auto;font-size:18px;color:#65656a}.body{height:407px;display:grid;grid-template-columns:213px 1fr}.art{height:407px;width:213px;object-fit:contain}.copy{padding:25px 29px 15px 20px;display:flex;flex-direction:column;min-width:0}h2{font-size:22px;line-height:1.27;font-weight:650;margin:0 0 23px;white-space:pre-wrap}.text{white-space:pre-line;font-size:13px;line-height:1.7;margin:0}.finish{margin-top:auto;padding-top:12px;font-size:13px}.finish label{gap:7px}.finish a{color:#51515b;display:inline-block;margin-top:15px;text-underline-offset:3px}.bottom{background:#f6f6f6;border-top:1px solid #dedee1;height:57px;padding:12px 16px;display:flex;gap:8px;justify-content:flex-end;align-items:center}.bottom button{font-size:12px;min-width:87px;padding:4px 10px;border-radius:2px}.primary{outline:1px solid #45454a;outline-offset:-2px}.note{color:#77777b;font-size:12px;margin-top:14px}.gallery{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:18px;border-top:1px solid #dcdce0;margin-top:32px;padding-top:24px}.gallery button{padding:0 0 8px;border:0;background:transparent}.gallery img{width:100%;height:175px;object-fit:contain;mix-blend-mode:multiply}.gallery button[aria-pressed=true]{border-bottom:2px solid #3d3d42}.gallery span{display:block;text-align:center;font-size:13px}.gallery button:hover{background:#eee}@media(max-width:700px){main{margin:28px auto;padding:0 18px}.gallery{grid-template-columns:repeat(3,1fr)}.gallery img{height:145px}}
</style><main><header><h1>Desktop Installer</h1><p>一套安装样式，各自的妹妹。切换项目、语言和页面，查看实际使用的立绘与文案。</p></header>
<div class="controls"><label>项目 <select id="product" aria-label="项目"></select></label><label>语言 <select id="language" aria-label="语言"><option value="zh-Hans">简体中文</option><option value="en">English</option><option value="ja">日本語</option></select></label><label>页面 <select id="page" aria-label="页面"><option value="welcome">欢迎</option><option value="finish">完成</option></select></label></div>
<div class="surface"><section class="window" aria-label="安装布局预览"><div class="titlebar"><span id="caption"></span><span class="close" aria-hidden="true">×</span></div><div class="body"><img id="art" class="art" alt=""><div class="copy"><h2 id="heading"></h2><p id="text" class="text"></p><div id="finish" class="finish"><label><input type="checkbox" checked disabled><span id="run"></span></label><a id="star" target="_blank" rel="noopener noreferrer"></a></div></div></div><div class="bottom"><button id="back"></button><button id="next" class="primary"></button><button id="cancel" disabled></button></div></section></div>
<p class="note">这是布局预览，不是 Windows 实机截图。文字和侧图来自公共源文件；最终字体、间距与缩放由 Windows 原生安装界面决定。</p><div class="gallery" id="gallery"></div></main>
<script>const data=${data};const $=id=>document.getElementById(id);for(const p of data.products){const o=new Option(p.name,p.id);$('product').add(o);const b=document.createElement('button');b.type='button';b.dataset.id=p.id;const i=document.createElement('img');i.src=p.image;i.alt='';const s=document.createElement('span');s.textContent=p.name;b.append(i,s);b.onclick=()=>{$('product').value=p.id;render()};$('gallery').append(b)}
const buttons={en:['Back','Next','Finish','Cancel','Run'], 'zh-Hans':['上一步','下一步','完成','取消','运行'],ja:['戻る','次へ','完了','キャンセル','起動']};
function render(){const p=data.products.find(p=>p.id===$('product').value),l=$('language').value,page=$('page').value,m=data.messages[l],done=page==='finish',b=buttons[l];document.querySelector('.window').lang=l;const fill=s=>s.replace(/\\{(\\w+)\\}/g,(_,k)=>({app:p.name,description:p.description[l],tip:p.tip[l]})[k]);$('caption').textContent=fill(m.installerCaption);$('heading').textContent=fill(m[page+'Title']);$('text').textContent=fill(m[page+'Text']);$('art').src=p.image;$('art').alt=p.name+' character';$('finish').hidden=!done;$('star').textContent=m.starLink;$('star').href=p.repository;$('run').textContent=b[4]+' '+p.name;$('back').textContent=b[0];$('back').disabled=!done;$('next').textContent=b[done?2:1];$('cancel').textContent=b[3];document.querySelectorAll('.gallery button').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.id===p.id)))}
for(const id of ['product','language','page'])$(id).onchange=render;$('next').onclick=()=>{$('page').value=$('page').value==='welcome'?'finish':'welcome';render()};$('back').onclick=()=>{$('page').value='welcome';render()};render();</script></html>`;
mkdirSync(join(destination, '..'), { recursive: true }); writeFileSync(destination, html); console.log(destination);
