import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { brotliCompressSync, brotliDecompressSync, constants } from 'node:zlib';
import { digest, decodeBundle } from './consumer.mjs';

export const root = fileURLToPath(new URL('..', import.meta.url));
export const productIds = readdirSync(join(root, 'products')).filter(f => /^[a-z][a-z0-9-]*\.json$/.test(f)).map(f => f.slice(0, -5)).sort();
export const languages = { en: ['English', 1033], 'zh-Hans': ['SimpChinese', 2052], ja: ['Japanese', 1041] };
export const version = JSON.parse(readFileSync(join(root, 'package.json'))).version;
export const layout = JSON.parse(readFileSync(join(root, 'src/layout.json')));
export const readProduct = id => {
  if (!productIds.includes(id)) throw new Error('Unknown product');
  const p = JSON.parse(readFileSync(join(root, 'products', `${id}.json`)));
  if (p.id !== id || typeof p.name !== 'string' || !p.name.trim() || p.name.length > 24 || /[$"\\\r\n]/.test(p.name) ||
      p.directory !== id || !/^https:\/\/github\.com\/[A-Za-z0-9][A-Za-z0-9-]*\/[A-Za-z0-9_.-]+$/.test(p.repository) ||
      typeof p.publisher !== 'string' || p.publisher.length > 32 || /[\r\n]/.test(p.publisher)) throw new Error('Invalid product profile');
  for (const key of ['description', 'tip']) {
    if (Object.keys(p[key]).sort().join() !== Object.keys(languages).sort().join() ||
        Object.values(p[key]).some(s => typeof s !== 'string' || s.length > 130 || /[\r\n]/.test(s))) {
      throw new Error(`Invalid localized ${key}`);
    }
  }
  return p;
};
const nsis = s => s.replaceAll('$', () => '$$').replaceAll('"', '$\\"').replaceAll('\n', '$\\r$\\n');
const bom = s => Buffer.from('\ufeff' + s, 'utf8');
const upper = s => s[0].toUpperCase() + s.slice(1);

export function readPreviewIcon(id) {
  if (!productIds.includes(id)) throw new Error('Unknown product');
  const manifest = JSON.parse(readFileSync(join(root, 'assets/preview-icons.json')));
  const entry = manifest.icons?.[id];
  const bytes = readFileSync(join(root, 'assets', id, 'preview.ico'));
  if (manifest.format !== 'yuxino-preview-icons-v1' || !entry || bytes.length !== entry.size ||
      digest(bytes) !== entry.sha256 || bytes.length < 6 || bytes.readUInt32LE(0) !== 0x00010000 ||
      bytes.readUInt16LE(4) === 0) throw new Error(`Invalid or corrupt preview icon: ${id}`);
  return bytes;
}

export function themeText(product) {
  const messages = JSON.parse(readFileSync(join(root, 'locales/messages.json')));
  const keys = ['installerCaption', 'uninstallerCaption', 'welcomeTitle', 'welcomeText', 'finishTitle', 'finishText', 'starLink', 'runText'];
  const lines = [
    '; Generated by @yuxino/desktop-installer. Tauri owns all installation behavior.',
    '!ifndef YUXINO_INSTALLER_THEME', '!define YUXINO_INSTALLER_THEME',
    '; Native language-specific UI fonts. Text is never baked into character artwork.',
    'SetFont /LANG=1033 "Segoe UI" 9',
    'SetFont /LANG=2052 "Microsoft YaHei UI" 9',
    'SetFont /LANG=1041 "Yu Gothic UI" 9',
    '!define MUI_BGCOLOR "FFFFFF"', '!define MUI_TEXTCOLOR "303038"',
    '!define MUI_WELCOMEFINISHPAGE_BITMAP_STRETCH AspectFitHeight',
    '!define MUI_INSTFILESPAGE_COLORS "303038 FFFFFF"',
  ];
  for (const [locale, [, id]] of Object.entries(languages)) {
    if (Object.keys(messages[locale] ?? {}).sort().join() !== [...keys].sort().join()) throw new Error('Translation keys differ');
    for (const key of keys) {
      const source = messages[locale][key];
      const replacements = { app: product.name, description: product.description[locale], tip: product.tip[locale] };
      const rendered = source.replace(/\{(\w+)\}/g, (_, token) => {
        if (!(token in replacements)) throw new Error(`Unknown translation token: ${token}`);
        return replacements[token];
      });
      lines.push(`LangString Yuxino${upper(key)} ${id} "${nsis(rendered)}"`);
    }
  }
  lines.push(
    'Caption "$(YuxinoInstallerCaption)"', 'UninstallCaption "$(YuxinoUninstallerCaption)"',
    '!define MUI_WELCOMEPAGE_TITLE "$(YuxinoWelcomeTitle)"',
    '!define MUI_WELCOMEPAGE_TEXT "$(YuxinoWelcomeText)"',
    '!define MUI_FINISHPAGE_TITLE "$(YuxinoFinishTitle)"',
    '!define MUI_FINISHPAGE_TEXT "$(YuxinoFinishText)"',
    '!define MUI_FINISHPAGE_TEXT_LARGE',
    '!define MUI_FINISHPAGE_RUN_TEXT "$(YuxinoRunText)"',
    '; Native link: opens only on a click. Passive updates skip Finish entirely.',
    '!define MUI_FINISHPAGE_LINK "$(YuxinoStarLink)"',
    `!define MUI_FINISHPAGE_LINK_LOCATION "${product.repository}"`,
    '!define MUI_FINISHPAGE_LINK_COLOR "62626A"',
  );
  lines.push(readFileSync(join(root, 'src/bitmap.nsh'), 'utf8'));
  const fields = { TITLE: 'title', WELCOME_TEXT: 'welcomeText', FINISH_TEXT: 'finishText', RUN: 'run', SHORTCUT: 'shortcut', LINK: 'link' };
  lines.push(readFileSync(join(root, 'src/layout.nsh'), 'utf8').replace(/@([A-Z_]+)@/g, (_, key) => {
    const rect = layout[fields[key]];
    if (!rect || Object.values(rect).some(n => !Number.isInteger(n) || n < 0)) throw new Error('Invalid native layout');
    return [rect.x, rect.y, rect.width, rect.height].join(' ');
  }), '!endif', '');
  return bom(lines.join('\n'));
}

export function compileProduct(id) {
  const product = readProduct(id);
  const art = JSON.parse(readFileSync(join(root, 'assets', id, 'bitmap.json')));
  if (art.portraitSha256 !== digest(readFileSync(join(root, 'assets', id, 'portrait.png')))) throw new Error('Stale character rendering');
  const sidebar = brotliDecompressSync(readFileSync(join(root, 'assets', id, 'sidebar.bmp.br')), { maxOutputLength: 2_471_862 });
  if (digest(sidebar) !== art.sha256) throw new Error('Corrupt character rendering');
  const files = { 'theme.nsh': themeText(product), 'sidebar.bmp': sidebar };
  for (const [name] of Object.values(languages)) {
    const source = readFileSync(join(root, 'locales', `${name}.nsh`), 'utf8');
    // Tauri prepends its own BOM when copying customLanguageFiles. A source
    // BOM would survive as an invalid command after NSIS consumes the first.
    files[`${name}.nsh`] = Buffer.from(source.replace(/^\ufeff+/, '').replaceAll('@APP@', product.name));
  }
  files['preview.nsi'] = bom(readFileSync(join(root, 'src/preview.nsi'), 'utf8').replaceAll('@APP@', product.name));
  const pack = { format: 'yuxino-installer-v2', version, product: id, files: {} };
  for (const name of Object.keys(files).sort()) {
    const data = files[name];
    pack.files[name] = { size: data.length, sha256: digest(data), data: data.toString('base64') };
  }
  const bytes = Buffer.from(JSON.stringify(pack));
  const compressed = brotliCompressSync(bytes, { params: { [constants.BROTLI_PARAM_QUALITY]: 9 } });
  const lock = { format: 'yuxino-installer-lock-v2', source: 'yuxino/desktop-installer', version, product: id, repository: product.repository,
    size: compressed.length, unpackedSize: bytes.length, sha256: digest(compressed) };
  decodeBundle(compressed, lock);
  return { product, files, compressed, lock };
}
